name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Set up our JDK environment'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11'

      - name: 'Make gradle executable'
        run: chmod +x gradlew

      - name: 'Build Project'
        run: ./gradlew --no-daemon build

      - name: 'Assemble Release'
        run: ./gradlew --no-daemon assembleRelease

      - name: 'Bundle Release AAB'
        run: ./gradlew --no-daemon bundleRelease

      ## Sign our artifact##
      - name: 'Sign artifact AAB'
        id: signAAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: smartsensors/build/outputs/bundle/release/
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: 'Sign artifact APK'
        id: signAPK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: smartsensors/build/outputs/apk/release/
          alias: ${{ secrets.KEYALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - run: find .

      - name: 'Create Release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: 'Upload AAB Artifact to release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.signAAB.outputs.signedReleaseFile }}
          asset_name: smartsensors.aab
          asset_content_type: application/zip

      - name: 'Upload APK Artifact to release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.signAPK.outputs.signedReleaseFile }}
          asset_name: smartsensors.apk
          asset_content_type: application/vnd.android.package-archiv
