name: Create Firmware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Set up our JDK environment'
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: 'Make gradle executable'
      run: chmod +x gradlew

    - name: 'Build APP'
      run: ./gradlew assembleRelease

    - run: find .

      ## Sign our artifact##
    - name: 'Sign artifact'
      id: signArtifact
      uses: r0adkll/sign-android-release@v1.0.1
      with:
        releaseDirectory: smartsensors/build/outputs/apk/release/
        alias: ${{ secrets.KEYALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: 'Upload our APK'
      uses: actions/upload-artifact@v2
      with:
        name: Release artifact
        path: smartsensors/build/outputs/apk/release/*.apk
