name: Create Firmware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Set up our JDK environment'
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'

    - name: 'Make gradle executable'
      run: chmod +x gradlew

    - name: 'Build Project'
      run: ./gradlew --no-daemon build

    - name: 'Assemble Release'
      run: ./gradlew --no-daemon assembleRelease

    - name: 'Bundle Release AAB'
      run: ./gradlew --no-daemon bundleRelease

    ## Sign our artifact##
    - name: 'Sign artifact AAB'
      id: signAAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: smartsensors/build/outputs/bundle/release/
        alias: ${{ secrets.KEYALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: 'Sign artifact APK'
      id: signAPK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: smartsensors/build/outputs/apk/release/
        alias: ${{ secrets.KEYALIAS }}
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - run: find .

    - name: 'Upload our ABB'
      uses: actions/upload-artifact@v2
      with:
        name: Release artifact AAB
        path: ${{ steps.signAAB.outputs.signedReleaseFile }}

    - name: 'Upload our APK'
      uses: actions/upload-artifact@v2
      with:
        name: Release artifact APK
        path: ${{ steps.signAPK.outputs.signedReleaseFile }}
